### ISSUE TITLE
Merge with homebridge-tuya

### ISSUE THREAD

**Issue by codetheweb** [SLaweck/homebridge-tuya-smartlamp#1]
Hey,

Looks like you have some great work here, I really appreciate all the effort you've put into this.  Do you want to consider merging your package with `homebridge-tuya`?

My goal is to eventually have the 'official' Homebridge package support virtually every type of Tuya device, and this can only be done with the help of community members.

**Comment by SLaweck** [comment]
Hi,
Currently, I really miss the time to finish my ideas :-(
I started to make this plugin for light bulbs, because none of them I liked. I still have good color and scene support to do. Now I'm finishing the sockets service with energy consumption monitoring and history recording for the Eve app.
So in a few weeks probably why not?

**Comment by codetheweb** [comment]
Sounds good, thanks. 😃
